# Please check the comments in the file to understand the parameters
apiVersion: batch/v1
kind: Job
metadata:
  name: vizpad-runner
  namespace: performance-testing
spec:
  # parallelism is the number of jobs to run concurrently
  # completions is the number of jobs to run to completion
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        app: vizpad
    spec:
      nodeSelector:
        env: performance-testing
      restartPolicy: Never
      containers:
        - name: vizpad
          # image is the image to run the job, please update the image tag to the latest version
          image: 956938892320.dkr.ecr.us-east-1.amazonaws.com/qa-automation:performance-v1.01
          # The command is updated to pass the '--users=2' argument to the 'vizpad' npm script.
          # The '--' is used to separate arguments for npm from arguments for your script.
          command: ["npm", "run", "vizpad", "--", "--users=3"]
          resources:
            requests:
              cpu: "7"
          volumeMounts:
            - name: test-reports
              mountPath: /app/testReports
      volumes:
        - name: test-reports
          emptyDir: {}
      imagePullSecrets:
       - name: tellius-ecr